nameOverride: ""
fullnameOverride: ""

replicaCount: 2

image:
  repository: my-spring-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: my-spring-app.local
      path: /
      pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

javaOpts: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=80"
